# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   qua mar 17 2021
# Processor: RPI3
# Compiler:  Python 3 (Proteus)

# Modules
from goto import *
import time
import var
import pio
import resource

# Peripheral Configuration Code (do not edit)
#---CONFIG_BEGIN---
import cpu
import FileStore
import VFP
import Generic

def peripheral_setup () :
# Peripheral Constructors
 pio.cpu=cpu.CPU ()
 pio.storage=FileStore.FileStore ()
 pio.server=VFP.VfpServer ()
 pio.LED1=Generic.LED (pio.GPIO20)
 pio.storage.begin ()
 pio.server.begin (0)
 #GPIOs
 #leitura da posicao
 cpu.pinMode(24,INPUT) 
 cpu.pinMode(25,INPUT) 
 #controle dos motores
 cpu.pinMode(17,OUTPUT)
 cpu.pinMode(18,OUTPUT)
 cpu.pinMode(27,OUTPUT)
 cpu.pinMode(22,OUTPUT)
 
# Install interrupt handlers

def peripheral_loop () :
 pass

#---CONFIG_END---

# Main function
def main () :
# Setup
 peripheral_setup()
   
# Infinite loop
 while 1 :
  peripheral_loop()
  #ler o estado da compra no arquivo  
  arquivo = open("statusCompra.bin","rb")
  status = arquivo.read(1)
  arquivo.close()
  
  #decdir se deve travar a roda
  if(status == 't'):	#travar a roda
	cpu.digitalWrite(17,1)
	cpu.digitalWrite(27,1)
	cpu.digitalWrite(18,0)
	cpu.digitalWrite(22,0)
  else:					#destravar a roda
	cpu.digitalWrite(17,0)
	cpu.digitalWrite(27,0)
	cpu.digitalWrite(18,1)
    cpu.digitalWrite(22,1)
  
  pass
# Command line execution
if __name__ == '__main__' :
   main()




