/* Main.c file generated by New Project wizard
 *
 * Processor: MSP430G2553
 * Compiler:  GCC for MSP430
 */

#include <MSP430.h>


int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
